### PR TITLE
Vast improvements

### PR DESCRIPTION
**Pull request by darth-kitty**
No, really

### CODE REVIEW

**Comment by darth-kitty** [comment]
A comment of some sort.

**Comment by darth-kitty** [comment]
See #1 for hilarious shenanigans, which is apparently a word that I cannot spell.

**Comment by brian-darthkitty-todd** [comment]
[shit, piss, fuck, cunt, cocksucker, motherfucker, tits](https://en.wikipedia.org/wiki/Seven_dirty_words)

**Comment by darth-kitty** [comment]
Thanks for doing this! :smiley:

**Pull request merged**
